<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Authors>Tomas Bouda</Authors>
    <Company>TomLabs</Company>
    <VersionPrefix>0.1.0</VersionPrefix>
    <RepositoryUrl>https://github.com/TomasBouda/TomLabs.AutoUpdate</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/TomasBouda/TomLabs.AutoUpdate</PackageProjectUrl>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
